import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { Col, Container, Row } from 'react-bootstrap'
import PageLayout from '../components/Layout'
import { ConnectionBox } from '../components/Layout/ConnectionBox'
import { MemeDetail } from '../components/MemeDetail'
import { RemixBtnBox } from '../components/Remix/RemixBtnBox'
import { RemixShareBox } from '../components/Remix/RemixShareBox'
import { LoginStatus } from '../models/Connection/connection.model'


const Home: NextPage = () => {
  const [loginStatus, setLoginStatus] = useState(LoginStatus.DISCONNECTED);

  const mockMeme = {
    src: "/assets/imgs/distracted boyfriend.png",
    mockProfile: {
      username: "cryptopunk",
      profilePic: "/assets/imgs/punk.png"
    },
    remixCount: 210,
    publicationDate: new Date()
  }

  const user = {};

  return (
    <div className='home-bg min-h-screen'>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" /> */}
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600&display=swap" rel="stylesheet" />
      </Head>
      <PageLayout>
        <Container fluid="md" className='h-full'>
          <Row className='mt-auto'>
            <Col>
              <article className='space-y-10'>
                {
                  loginStatus !== LoginStatus.CONNECTED ?
                    <Row>
                      <Col>
                        <header>
                          <ConnectionBox status={loginStatus} />
                        </header>
                      </Col>
                    </Row>
                  : null
                }
                <Row>
                  <Col>
                    <section className='flex flex-col sm:flex-col lg:flex-row gap-6'>
                      <MemeDetail meme={mockMeme} />
                      <div className='flex flex-col space-y-10 w-full h-auto'>
                        <RemixBtnBox />
                        <RemixShareBox />
                      </div>
                    </section>
                  </Col>
                </Row>
              </article>
            </Col>
          </Row>
        </Container>

      </PageLayout>
    </div>
  )
}

export default Home
