import type { NextPage } from 'next'
import Head from 'next/head'
import { Col, Container, Row } from 'react-bootstrap'
import PageLayout from '../../components/Layout'

type ProfileProps = {
    createdMemmes: any[]
  }

const Profile: NextPage = (props: any) => {
    const mockMeme = {
        src: "/assets/imgs/distracted boyfriend.png",
        mockProfile: {
            username: "cryptopunk",
            profilePic: "/assets/imgs/punk.png"
        },
        remixCount: 210,
        publicationDate: new Date()
    }

    return (
        <div className='profile-bg h-screen'>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600&display=swap" rel="stylesheet" />
            </Head>
            <PageLayout>
                <Container fluid="md">
                    <Row>
                        <Col>

                        </Col>
                    </Row>
                    <Row>
                        <Col>
                            <article className='space-y-10'>

                            </article>
                        </Col>
                    </Row>
                </Container>
            </PageLayout>
        </div>
    )
}

export const getStaticProps = async ({ params }: any): Promise<{ props: ProfileProps }> => {
  
    //TODO retrieve memes from user with apollo
  
    return {
      props: {
        createdMemmes: [],
      }
    }
  
  }

export default Profile
