import { Html, Head, Main, NextScript } from 'next/document'

declare global {
  interface Window {
    wpcc?: any;
  }
}

const Document = () => {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600&display=swap" rel="stylesheet" />
        <script src="https://cdn.websitepolicies.io/lib/cookieconsent/cookieconsent.min.js" defer></script><script>window.addEventListener("load",function(){window.wpcc.init({"border":"thin","corners":"small","colors":{"popup":{"background":"#f6f6f6","text":"#000000","border":"#555555"},"button":{"background":"#555555","text":"#ffffff"}}})});</script>
      </Head>
      <body className='home-bg min-h-screen'>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

export default Document;
